[package]
name = "jasyptenc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = [ "derive" ] }
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
pbkdf2 = "0.12.2"
aes = "0.8.4"
cbc = { version = "0.1.2", features = [ "std" ] }
base64 = "0.22.0"